<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-T9LQH1T" failures="1" tests="9" name="Default test" time="42.327" errors="0" timestamp="2024-04-19T19:40:58 IST">
  <testcase classname="testCases.Verify_Multiple_Crediential" name="loginToApplicationTest" time="1.893"/>
  <testcase classname="testCases.Verify_Multiple_Crediential" name="logintoApplicationWithMultipleCredsTest" time="1.498"/>
  <testcase classname="testCases.Verify_Multiple_Crediential" name="logintoApplicationWithMultipleCredsTest" time="1.168">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [https://www.saucedemo.com/] but found [https://www.saucedemo.com/inventory.html]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://www.saucedemo.com/] but found [https://www.saucedemo.com/inventory.html]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testCases.Verify_Multiple_Crediential.logintoApplicationWithMultipleCredsTest(Verify_Multiple_Crediential.java:71)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- logintoApplicationWithMultipleCredsTest -->
  <testcase classname="testCases.Verify_Multiple_Crediential" name="logintoApplicationWithMultipleCredsTest" time="0.62"/>
  <testcase classname="testCases.Verify_Multiple_Crediential" name="logintoApplicationWithMultipleCredsTest" time="5.59"/>
  <testcase classname="testCases.Verify_Multiple_Crediential" name="logintoApplicationWithMultipleCredsTest" time="0.664"/>
  <testcase classname="testCases.Verify_Multiple_Crediential" name="logintoApplicationWithMultipleCredsTest" time="0.566"/>
  <testcase classname="testCases.Verify_Multiple_Crediential" name="verifyTitleOfApplicationTest" time="0.1"/>
  <testcase classname="testCases.Verify_Multiple_Crediential" name="verifyURLOfApplication" time="0.772"/>
</testsuite> <!-- Default test -->
